@PlanService_HostAddress = http://localhost:5260



### Get All
GET {{PlanService_HostAddress}}/api/plans/
Accept: application/json

### Get By Id
GET {{PlanService_HostAddress}}/api/plans/2
Accept: application/json
