@PlanService_HostAddress = http://localhost:5260



### Get All
GET {{PlanService_HostAddress}}/api/plans/
Accept: application/json

### Get By Id
GET {{PlanService_HostAddress}}/api/plans/2
Accept: application/json

### Create New Plan
POST {{PlanService_HostAddress}}/api/plans
Content-Type: application/json

{
  "name": "Test Fluent Validation",
  "description": "string",
  "contributionAmount": 10,
  "coverageAmount": 20,
  "minEntryAge": 18,
  "maxEntryAge": 60
}

### Delete Plan
DELETE {{PlanService_HostAddress}}/api/plans/1011
Content-Type: application/json

### Create New Plan
PATCH {{PlanService_HostAddress}}/api/plans/1014
Content-Type: application/json

{
  "name": "Test Updating Fluent Validation",
  "description": "I am patching data now",
  "contributionAmount": 10,
  "coverageAmount": 20,
  "minEntryAge": 56,
  "maxEntryAge": 60
}
